version: '3.1'
services:
  refactor-me:
    container_name: refactor-me
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - refactor-me-network

  refactor-me-postgres:
    image: postgres:alpine
    container_name: refactor-me-postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./.env
    networks:
      - refactor-me-network

networks:
  refactor-me-network:
    driver: bridge
